### ISSUE TITLE
Color function "color" is not supported

### ISSUE THREAD

**Issue by enjoijkee** [yorickshan/html2canvas-pro#1]
Take this issue as a feature request as I couldn't find the parsing of the "color" function in the source code.
When trying to convert a component with "color" function to canvas I'm getting the error `Attempting to parse an unsupported color function "color"`.
<img width="480" alt="Screenshot 2024-05-13 at 23 59 32" src="https://github.com/yorickshan/html2canvas-pro/assets/9976361/eec6b572-6720-43e4-89c5-949da508272e">
<img width="601" alt="Screenshot 2024-05-13 at 23 35 14" src="https://github.com/yorickshan/html2canvas-pro/assets/9976361/d0660e42-b432-4270-adda-a4b06029ca5f">

### Specifications:

 * html2canvas-pro version tested with: 1.4.3
 * Browser & version: Opera GX 107.0.5045.89 (Chromium 121.0.6167.186)
 * Operating system: macOS Sonoma 14.4.1

**Comment by johnson-jesse** [comment]
Seeing the same issue with Chrome Version 125.0.6422.60 (Official Build) (x86_64)

**Comment by yorickshan** [comment]
try v1.5.0

**Comment by yorickshan** [comment]
> Seeing the same issue with Chrome Version 125.0.6422.60 (Official Build) (x86_64)

v1.5.0

**Comment by enjoijkee** [comment]
> try v1.5.0

Works perfectly, thank you guys!
