### ISSUE TITLE
Fix Firefox issue: CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0

### ISSUE THREAD

**Issue by Azahliil** [yorickshan/html2canvas-pro#7]
### Bug report:

I recently came to using html2canvas-pro and ran into the following issue when trying to create a PDF using html2canvas-pro and jsPDF:

```
DOMException: CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0
```

Which seems to be an old issue from html2canvas (https://github.com/niklasvh/html2canvas/issues/2697)

There is also a potential fix mentioned in the above issue (https://github.com/Nexedi/erp5/commit/d4974e48408b823809757a2a5538fe43f6b71ea9)

For now I patched html2canvas-pro via patch-package to include the fix and so far I haven't notices any adverse effects, so I was wondering if the changes could just be included, removing the need for a manual patch and making it more compatible with Firefox.

I have prepared a little PR with the changes for your convenience #8 

### Specifications:

 * html2canvas-pro version tested with: 1.5.1
 * Browser & version: Firefox 127.0.2
 * Operating system: MacOS 14.5

**Comment by yorickshan** [comment]
hi, thx for your pr, fix for firefox has been merged in v1.5.3 of html2canvas-pro. If you encounter any issues with html2canvas-pro or have suggestions for new features, feel free to submit a PR. I'll address it as soon as possible.
